import { KILN_VALIDATORS as v } from "./validators";
import createClient, { Client } from "openapi-fetch";
import type { paths } from "../openapi/schema";
import { FireblocksService } from "./services/fireblocks"; // generated by openapi-typescript

type Config = {
  baseUrl: string;
  apiToken: string;
};

export const KILN_VALIDATORS = v;

export class Kiln {
  fireblocks: FireblocksService;
  client: Client<paths>;

  constructor({ apiToken, baseUrl }: Config) {
    const client = createClient<paths>({ baseUrl, headers: { Authorization: `Bearer ${apiToken}` } });
    this.fireblocks = new FireblocksService(client);
    this.client = client;
  }
}
