name: "sdk-js"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/sdk.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/sdk.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "setup:bun"
        uses: oven-sh/setup-bun@v1
      - name: "install-deps"
        run: bun install
      - name: "lint"
        run: bun run lint
      - name: "build"
        run: bun run build
