name: "sdk-js"

on:
  push:
    branches:
      - main
    paths:
      - "src/**
      - "index.ts"
  pull_request:
    branches:
      - main
    paths:
      - "src/**
      - "index.ts"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint

