name: "sdk-js"

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "index.ts"
      - ".github/workflows/sdk.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "index.ts"
      - ".github/workflows/sdk.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
